# Works well with my dualshock 4 controller
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 3
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.7

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 3.0
    scale_angular_turbo:
      yaw: 6.0

    enable_button: 7  # L2 shoulder button
    enable_turbo_button: 6  # L1 shoulder button
